---
services:
  autoscaler:
    build: ./autoscaler
    container_name: gitlab-autoscaler
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      - TZ=Europe/Moscow
    labels:
      - 'autoscaler=true'
